### ISSUE TITLE
Unautorized request does not return CORS headers

### ISSUE THREAD

**Issue by josbol** [seanonline/Webapi_JWT_Authentication#2]
Hi!

When testing your code, everything seems to be fine, and I really like your solution over the more cumbersome alternative solutions, but there seems to be a problem when using CORS in case of an unauthorized request (401), possibly even all failed requests (4xx and 5xx): 

When a request is made to a controller action decorated with [Authorize] and using an invalid or expired token, a 401 response is returned as expected, but the CORS headers are not being returned. This causes the client not being able to recognize the status code.

Steps to replicate:

1. Set up a Web.API project as described in your blog post
2. Install Microsoft.AspNet.WebApi.Cors (currently 5.2.6)
3. Enable it in WebApiConfig:   
```
// Not restricting anything while debugging 
var cors = new System.Web.Http.Cors.EnableCorsAttribute("*", "*", "*");
config.EnableCors(cors);
```
4. Decorate a controller action with [Authorize]
5. Make a call to the controller action from a different domain (or at least a different port), using an expired token
6. The response will be 401, but without CORS Headers

The cause is line 76:

`return Task<HttpResponseMessage>.Factory.StartNew(() => new HttpResponseMessage(statusCode) { });`

Changing this line to the following will solve the issue::

` return base.SendAsync(request, cancellationToken)`

Since this solution pushes the request further down the pipeline, instead of immediately returning, this solution consumes more resources for each request, so this might not be the right solution for everybody. Alternatively one could manually add the missing headers before returning, but I don't think that would be a good idea.

Would you by any chance have a better solution for this problem?

**Comment by seanonline** [comment]
Thanks . will look into it some time this week.

**Comment by seanonline** [comment]
resolved this current comment. code checked in
